### ISSUE TITLE
Text to add to the "join" page

### ISSUE THREAD

**Issue by helsf** [Department-of-Decentralization/ETHBerlinZwei#15]
Can we add the following on the "Join" page please :)

Press & Media
For all press requests or media enquiries please contact Helena Flack, helena@ethberlin.com

**Comment by helsf** [comment]
and put it on the top seeing as the other applications are closed!

**Comment by ligi** [comment]
https://github.com/Department-of-Decentralization/ETHBerlinZwei/pull/16

changed your email to like it is below

**Comment by helsf** [comment]
Thanks @ligi !
